select * from Banks
select * from Branches
select * from Roles
select * from Departments
select * from Designations
select * from Employees
select * from Leaves
select * from leavetypes
select * from Tx_History
select * from EmployeeHistory
select * from deliverydate_ptl
select * from HolidayList
select * from Branch_Designation_Mapping
select * from EmpLeaveBalance
select * from LeaveInfo
select * from WorkingDays
