Update employees set controllingauthority=(select id from employees where lastName like '%RAVINDER Rao%') WHERE empid=686;	                        							
Update employees set controllingauthority=(select id from employees where lastName like '%Dr. N%' and  firstname like 	'%MURALIDHAR%') WHERE empid=462;	       
Update employees set controllingauthority=(select id from employees where lastName like '%Dr. N%' and  firstname like 	'%MURALIDHAR%') WHERE empid=354;	       
Update employees set controllingauthority=(select id from employees where lastName like '%Dr. N%' and  firstname like 	'%MURALIDHAR%') WHERE empid=405;	       
Update employees set controllingauthority=(select id from employees where lastName like '%Dr. N%' and  firstname like 	'%MURALIDHAR%') WHERE empid=271;	       
Update employees set controllingauthority=(select id from employees where lastName like '%MANZOOR%' and  firstname like 	'%GHOUSIA%') WHERE empid=460;	   
Update employees set controllingauthority=(select id from employees where lastName like '%Dr. N%' and  firstname like 	'%MURALIDHAR%') WHERE empid=463;	       
Update employees set controllingauthority=(select id from employees where lastName like '%MANZOOR%' and  firstname like 	'%GHOUSIA%') WHERE empid=204;	   
Update employees set controllingauthority=(select id from employees where lastName like '%N VANI%' and  firstname like 	'%BALA%') WHERE empid=266;	       
Update employees set controllingauthority=(select id from employees where lastName like '%Dr. N%' and  firstname like 	'%MURALIDHAR%') WHERE empid=368;	       
Update employees set controllingauthority=(select id from employees where lastName like '%MANZOOR%' and  firstname like 	'%GHOUSIA%') WHERE empid=371;	   
Update employees set controllingauthority=(select id from employees where lastName like '%K ANANTH%' and  firstname like 	'%RAO%') WHERE empid=383;	       
Update employees set controllingauthority=(select id from employees where lastName like '%MANZOOR%' and  firstname like 	'%GHOUSIA%') WHERE empid=279;	   
Update employees set controllingauthority=(select id from employees where lastName like 'A' and  firstname like 	'%NAGESWARI%') WHERE empid=377;	   
Update employees set controllingauthority=(select id from employees where lastName like 'M' and  firstname like 	'%SURESH%') WHERE empid=725;	   
Update employees set controllingauthority=(select id from employees where lastName like '%CHANDRASEKHAR%' and  firstname like 	'P') WHERE empid=1930;	       
Update employees set controllingauthority=(select id from employees where lastName like 'T' and  firstname like 	'%JYOTHI%'  ) WHERE empid=1862;	   
Update employees set controllingauthority=(select id from employees where lastName like 'M.' and  firstname like 	'%RAYAPPA%' ) WHERE empid=178;	       
Update employees set controllingauthority=(select id from employees where lastName like '%NIRMALA KUMARI%' and  firstname like	'Y') WHERE empid=250;	       
Update employees set controllingauthority=(select id from employees where lastName like '%KHAJA MOIN%' and  firstname like 	'%SHARIEF%') WHERE empid=249;	       
Update employees set controllingauthority=(select id from employees where lastName like 'B' and  firstname like 	'%SHAMALA%') WHERE empid=5751;	   
Update employees set controllingauthority=(select id from employees where lastName like '%K RAJESHWAR%' and  firstname like 	'%RAO%') WHERE empid=5740;	   
Update employees set controllingauthority=(select id from employees where lastName like '%T.B.%' and  firstname like 	'%V.R SRINIVASA RAO%') WHERE empid=301; 
Update employees set controllingauthority=(select id from employees where lastName like '%N VANI%' and  firstname like 	'%BALA%') WHERE empid=302;	       
Update employees set controllingauthority=(select id from employees where lastName like '%CHANDRASEKHAR%' and  firstname like 	'P') WHERE empid=308;	       
Update employees set controllingauthority=(select id from employees where lastName like '%CHANDRASEKHAR%' and  firstname like 	'P') WHERE empid=5862;	       
Update employees set controllingauthority=(select id from employees where lastName like '%MANZOOR%' and  firstname like 	'%GHOUSIA%') WHERE empid=5796;	   
Update employees set controllingauthority=(select id from employees where lastName like '%CH CHINNA%' and  firstname like 	'%RAO%') WHERE empid=5869;	       
Update employees set controllingauthority=(select id from employees where lastName like '%B GANESH%' and  firstname like 	'%LAL%') WHERE empid=5884;	       
Update employees set controllingauthority=(select id from employees where lastName like '%SETTI SRINIVASA%' and  firstname like 	'%RAO%') WHERE empid=5889;	   
Update employees set controllingauthority=(select id from employees where lastName like '%B GANESH%' and  firstname like 	'%LAL%') WHERE empid=5909;	       
Update employees set controllingauthority=(select id from employees where lastName like '%CHANDRASEKHAR%' and  firstname like 	'P') WHERE empid=422;	       
Update employees set controllingauthority=(select id from employees where lastName like '%KHAJA MOIN%' and  firstname like 	'%SHARIEF%') WHERE empid=440;	       
Update employees set controllingauthority=(select id from employees where lastName like '%B GANESH%' and  firstname like 	'%LAL%') WHERE empid=6193;	       
Update employees set controllingauthority=(select id from employees where lastName like '%K ANANTH%' and  firstname like 	'%RAO%') WHERE empid=6196;	       
Update employees set controllingauthority=(select id from employees where lastName like '%B GANESH%' and  firstname like 	'%LAL%') WHERE empid=6198;	       
Update employees set controllingauthority=(select id from employees where lastName like '%B GANESH%' and  firstname like 	'%LAL%') WHERE empid=474;	       
Update employees set controllingauthority=(select id from employees where lastName like '%SRINIVASA RAO%' and  firstname like 	'%TBVR%') WHERE empid=491;	      
Update employees set controllingauthority=(select id from employees where lastName like 'V' and  firstname like 	'%VENKATESWARLU%'   )     WHERE empid=492;	   
Update employees set controllingauthority=(select id from employees where lastName like '%CH CHINNA%' and  firstname like 	'%RAO%') WHERE empid=499;	       
Update employees set controllingauthority=(select id from employees where  LastName like 'M.' and  firstname like 	'%RAYAPPA%') WHERE empid=5890;	       
Update employees set controllingauthority=(select id from employees where lastName like '%K ANANTH%' and  firstname like 	'%RAO%') WHERE empid=510;	       
Update employees set controllingauthority=(select id from employees where lastName like '%CHANDRASEKHAR%' and  firstname like 	'p') WHERE empid=511;	       
Update employees set controllingauthority=(select id from employees where lastName like '%CHANDRASEKHAR%' and  firstname like 	'p') WHERE empid=512;	       
Update employees set controllingauthority=(select id from employees where lastName like '%KHAJA MOIN%' and  firstname like 	'%SHARIEF%') WHERE empid=523;	       
Update employees set controllingauthority=(select id from employees where lastName like '%SRINIVASA RAO%' and  firstname like 	'%MR%') WHERE empid=532;	       
Update employees set controllingauthority=(select id from employees where lastName like '%B GANESH%' and  firstname like 	'%LAL%') WHERE empid=535;	       
Update employees set controllingauthority=(select id from employees where lastName like '%B GANESH%' and  firstname like 	'%LAL%') WHERE empid=539;	       
Update employees set controllingauthority=(select id from employees where lastName like '%K RAJESHWAR%' and  firstname like 	'%RAO%') WHERE empid=544;	   
Update employees set controllingauthority=(select id from employees where lastName like '%D NAGA%' and  firstname like 	'%KRISHNA%') WHERE empid=831;	       
Update employees set controllingauthority=(select id from employees where lastName like '%DEVAKI%' and  firstname like 	'%JYOTHI%') WHERE empid=832;	       
Update employees set controllingauthority=(select id from employees where lastName like '%K RAJESHWAR%' and  firstname like 	'%RAO%') WHERE empid=833;	   
Update employees set controllingauthority=(select id from employees where lastName like '%B GANESH%' and  firstname like 	'%LAL%') WHERE empid=940;	       
Update employees set controllingauthority=(select id from employees where lastName like '%K RAJESHWAR%' and  firstname like 	'%RAO%') WHERE empid=950;	   
									
