update employees set SanctioningDepartment=(select id from departments where name='MD Office') where empid=686	;	
update employees set SanctioningDepartment=(select id from departments where name='CGM Office') where empid=462	;	
update employees set SanctioningDepartment=(select id from departments where name='GM Office') where empid=354	;	
update employees set SanctioningDepartment=(select id from departments where name='GM Office') where empid=405	;	
update employees set SanctioningDepartment=(select id from departments where name='GM Office') where empid=271	;	
update employees set SanctioningDepartment=(select id from departments where name='P&D DeptDept') where empid=460	;	
update employees set SanctioningDepartment=(select id from departments where name='IT Dept - EPD') where empid=463	;	
update employees set SanctioningDepartment=(select id from departments where name='L&A-PMU') where empid=204	;	
update employees set SanctioningDepartment=(select id from departments where name='Banking') where empid=266	;	
update employees set SanctioningDepartment=(select id from departments where name='IT Dept - EPD') where empid=368	;	
update employees set SanctioningDepartment=(select id from departments where name='Legal, Vigilance & RTI Act') where empid=371	;	
update employees set SanctioningDepartment=(select id from departments where name='TSCAB-CTI') where empid=383	;	
update employees set SanctioningDepartment=(select id from departments where name='DOS') where empid=279	;	
update employees set SanctioningDepartment=(select id from departments where name='CLPC') where empid=377	;	
update employees set SanctioningDepartment=(select id from departments where name='CGM Secretariat') where empid=1862	;	
update employees set SanctioningDepartment=(select id from departments where name='MD Secretariat') where empid=178	;	
update employees set SanctioningDepartment=(select id from departments where name='L&A-PMU') where empid=250	;	
update employees set SanctioningDepartment=(select id from departments where name='Banking') where empid=249	;	
update employees set SanctioningDepartment=(select id from departments where name='L&A-PMU') where empid=5751	;	
update employees set SanctioningDepartment=(select id from departments where name='Premises') where empid=5740	;	
update employees set SanctioningDepartment=(select id from departments where name='President secretariat') where empid=301	;	
update employees set SanctioningDepartment=(select id from departments where name='GM secretariat') where empid=302	;	
update employees set SanctioningDepartment=(select id from departments where name='Watchman') where empid=308	;	
update employees set SanctioningDepartment=(select id from departments where name='Watchman') where empid=5862	;	
update employees set SanctioningDepartment=(select id from departments where name='GM secretariat') where empid=5796	;	
update employees set SanctioningDepartment=(select id from departments where name='TSCAB-CTI') where empid=5869	;	
update employees set SanctioningDepartment=(select id from departments where name='Courier') where empid=5884	;	
update employees set SanctioningDepartment=(select id from departments where name='IT Dept - EPD') where empid=5889	;	
update employees set SanctioningDepartment=(select id from departments where name='Courier') where empid=5909	;	
update employees set SanctioningDepartment=(select id from departments where name='Watchman') where empid=422	;	
update employees set SanctioningDepartment=(select id from departments where name='Banking') where empid=440	;	
update employees set SanctioningDepartment=(select id from departments where name='Courier') where empid=6193	;	
update employees set SanctioningDepartment=(select id from departments where name='BRCC') where empid=6196	;	
update employees set SanctioningDepartment=(select id from departments where name='Clearing Dept') where empid=6198	;	
update employees set SanctioningDepartment=(select id from departments where name='Courier') where empid=474	;	
update employees set SanctioningDepartment=(select id from departments where name='President secretariat') where empid=491	;	
update employees set SanctioningDepartment=(select id from departments where name='DOS') where empid=492	;	
update employees set SanctioningDepartment=(select id from departments where name='MD Secretariat') where empid=499	;	
update employees set SanctioningDepartment=(select id from departments where name='TSCAB-CTI') where empid=5890	;	
update employees set SanctioningDepartment=(select id from departments where name='Banking - Risk Management Dept') where empid=510	;	
update employees set SanctioningDepartment=(select id from departments where name='HRD') where empid=511	;	
update employees set SanctioningDepartment=(select id from departments where name='Watchman') where empid=512	;	
update employees set SanctioningDepartment=(select id from departments where name='Banking') where empid=523	;	
update employees set SanctioningDepartment=(select id from departments where name='Legal, Vigilance & RTI Act') where empid=532	;	
update employees set SanctioningDepartment=(select id from departments where name='Courier') where empid=535	;	
update employees set SanctioningDepartment=(select id from departments where name='Courier') where empid=539	;	
update employees set SanctioningDepartment=(select id from departments where name='Inward-Outward') where empid=544	;	
update employees set SanctioningDepartment=(select id from departments where name='Board Secretariat') where empid=831	;	
update employees set SanctioningDepartment=(select id from departments where name='P&D Dept') where empid=832	;	
update employees set SanctioningDepartment=(select id from departments where name='CCTV') where empid=833	;	
update employees set SanctioningDepartment=(select id from departments where name='Courier') where empid=940	;	
update employees set SanctioningDepartment=(select id from departments where name='Xerox Dept') where empid=950	;	
