update employees set MobileNumber=8019597749	where empid=555	;
update employees set MobileNumber=7396905143	where empid=565	;
update employees set MobileNumber=8297002626	where empid=708	;
update employees set MobileNumber=9966003363	where empid=777	;
update employees set MobileNumber=8886477788	where empid=785	;
update employees set MobileNumber=9700697835	where empid=563	;
update employees set MobileNumber=9704295370	where empid=822	;
update employees set MobileNumber=9963932878	where empid=574	;
update employees set MobileNumber=8885463328	where empid=744	;
update employees set MobileNumber=97057993299	where empid=564	;
update employees set MobileNumber=8897062727	where empid=800	;
update employees set MobileNumber=8121519087	where empid=560	;
update employees set MobileNumber=8790265195	where empid=554	;
update employees set MobileNumber=7842716088	where empid=580	;
update employees set MobileNumber=9491347351	where empid=557	;
update employees set MobileNumber=9000961080	where empid=575	;
update employees set MobileNumber=9849668987	where empid=788	;
update employees set MobileNumber=8019857712	where empid=566	;
update employees set MobileNumber=9666657363	where empid=817	;
update employees set MobileNumber=9948461006	where empid=547	;
update employees set MobileNumber=9160152142	where empid=548	;
update employees set MobileNumber=9618010961	where empid=721	;
update employees set MobileNumber=9010470044	where empid=789	;
update employees set MobileNumber=8125819826	where empid=779	;
update employees set MobileNumber=9550275226	where empid=562	;
update employees set MobileNumber=9948460246	where empid=586	;
update employees set MobileNumber=9848445441	where empid=590	;
update employees set MobileNumber=9618966597	where empid=782	;
update employees set MobileNumber=8500091349	where empid=827	;
update employees set MobileNumber=9666966006	where empid=790	;
update employees set MobileNumber=9550475773	where empid=749	;
update employees set MobileNumber=9849414035	where empid=723	;
update employees set MobileNumber=8099086925	where empid=714	;
update employees set MobileNumber=9866142776	where empid=793	;
update employees set MobileNumber=9492821164	where empid=731	;
update employees set MobileNumber=9985883367	where empid=775	;
update employees set MobileNumber=9705945795	where empid=733	;
update employees set MobileNumber=7569019403	where empid=801	;
update employees set MobileNumber=9000134666	where empid=549	;
update employees set MobileNumber=8686593293	where empid=804	;
update employees set MobileNumber=8179645383	where empid=730	;
update employees set MobileNumber=9160615135	where empid=581	;
update employees set MobileNumber=8019475668	where empid=559	;
update employees set MobileNumber=9848244926	where empid=570	;
update employees set MobileNumber=9703312135	where empid=702	;
update employees set MobileNumber=9640815368	where empid=783	;
update employees set MobileNumber=8106204228	where empid=599	;
update employees set MobileNumber=9030906290	where empid=725	;
update employees set MobileNumber=9505847873	where empid=830	;
update employees set MobileNumber=9704097332	where empid=786	;
update employees set MobileNumber=9908757567	where empid=796	;
update employees set MobileNumber=8374361237	where empid=550	;
update employees set MobileNumber=9542353651	where empid=572	;
update employees set MobileNumber=9963164911	where empid=760	;
update employees set MobileNumber=9032861506	where empid=709	;
update employees set MobileNumber=8019341745	where empid=556	;
update employees set MobileNumber=9949355624	where empid=805	;
update employees set MobileNumber=7794877776	where empid=814	;
update employees set MobileNumber=9849537613	where empid=598	;
update employees set MobileNumber=8686837196	where empid=763	;
update employees set MobileNumber=9912506994	where empid=815	;
update employees set MobileNumber=9177313005	where empid=835	;
update employees set MobileNumber=9948479596	where empid=840	;
update employees set MobileNumber=9652550851	where empid=845	;
update employees set MobileNumber=8886985378	where empid=876	;
update employees set MobileNumber=7842721088	where empid=863	;
update employees set MobileNumber=8686889089	where empid=864	;
update employees set MobileNumber=9849417165	where empid=838	;
update employees set MobileNumber=7658906264	where empid=841	;
update employees set MobileNumber=8008872406	where empid=836	;
update employees set MobileNumber=9010984021	where empid=846	;
update employees set MobileNumber=9494462476	where empid=837	;
update employees set MobileNumber=9550367260	where empid=847	;
update employees set MobileNumber=8688630699	where empid=877	;
update employees set MobileNumber=8497996661	where empid=931	;
update employees set MobileNumber=8341566599	where empid=935	;
update employees set MobileNumber=9666460844	where empid=899	;
update employees set MobileNumber=8341473094	where empid=848	;
update employees set MobileNumber=8790568731	where empid=865	;
update employees set MobileNumber=9849752526	where empid=842	;
update employees set MobileNumber=8125953667	where empid=878	;
update employees set MobileNumber=8099546489	where empid=911	;
update employees set MobileNumber=9553574949	where empid=866	;
update employees set MobileNumber=9030332932	where empid=849	;
update employees set MobileNumber=7207455130	where empid=901	;
update employees set MobileNumber=7732023281	where empid=889	;
update employees set MobileNumber=9700138091	where empid=902	;
update employees set MobileNumber=9848284116	where empid=867	;
update employees set MobileNumber=9493054423	where empid=903	;
update employees set MobileNumber=9866460454	where empid=887	;
update employees set MobileNumber=9676127378	where empid=910	;
update employees set MobileNumber=9030505750	where empid=868	;
update employees set MobileNumber=8185945176	where empid=896	;
update employees set MobileNumber=8106583273	where empid=884	;
update employees set MobileNumber=7396299059	where empid=893	;
update employees set MobileNumber=9959739894	where empid=862	;
update employees set MobileNumber=7893470400	where empid=871	;
update employees set MobileNumber=9700399458	where empid=872	;
update employees set MobileNumber=8500923254	where empid=860	;
update employees set MobileNumber=9948642557	where empid=886	;
update employees set MobileNumber=8179536599	where empid=881	;
update employees set MobileNumber=9550649640	where empid=909	;
update employees set MobileNumber=9000730971	where empid=853	;
update employees set MobileNumber=9030875876	where empid=912	;
update employees set MobileNumber=9494195677	where empid=885	;
update employees set MobileNumber=9063451005	where empid=891	;
update employees set MobileNumber=9603845652	where empid=854	;
update employees set MobileNumber=9490343085	where empid=905	;
update employees set MobileNumber=8008142548	where empid=892	;
update employees set MobileNumber=9951553556	where empid=890	;
update employees set MobileNumber=8297588124	where empid=855	;
update employees set MobileNumber=7093430615	where empid=861	;
update employees set MobileNumber=9014889559	where empid=856	;
update employees set MobileNumber=8125373959	where empid=857	;
update employees set MobileNumber=9550609171	where empid=858	;
update employees set MobileNumber=9959523197	where empid=895	;
update employees set MobileNumber=9494248203	where empid=859	;
update employees set MobileNumber=9032018090	where empid=913	;
update employees set MobileNumber=9550856186	where empid=906	;
update employees set MobileNumber=7659040748	where empid=898	;
update employees set MobileNumber=7036393035	where empid=844	;
update employees set MobileNumber=9491542425	where empid=874	;
update employees set MobileNumber=7207676656	where empid=914	;
update employees set MobileNumber=9573735129	where empid=920	;
update employees set MobileNumber=9885501742	where empid=915	;
update employees set MobileNumber=9440952835	where empid=917	;
update employees set MobileNumber=8801869008	where empid=916	;
update employees set MobileNumber=9700319446	where empid=918	;
update employees set MobileNumber=9573128488	where empid=921	;
update employees set MobileNumber=8595224125	where empid=922	;
update employees set MobileNumber=7799122771	where empid=924	;
update employees set MobileNumber=7032250820	where empid=925	;
update employees set MobileNumber=9849117085	where empid=926	;
update employees set MobileNumber=8099080804	where empid=928	;
update employees set MobileNumber=9490899779	where empid=929	;
update employees set MobileNumber=9030602970	where empid=941	;
update employees set MobileNumber=7386435618	where empid=942	;
update employees set MobileNumber=9603815912	where empid=944	;
update employees set MobileNumber=9666110207	where empid=946	;
update employees set MobileNumber=9133772856	where empid=948	;
update employees set MobileNumber=9951749669	where empid=949	;
update employees set MobileNumber=8790967458	where empid=938	;
update employees set MobileNumber=7386762126	where empid=939	;
update employees set MobileNumber=9704000448	where empid=937	;
update employees set MobileNumber=9951126571	where empid=936	;
update employees set MobileNumber=8179736557	where empid=934	;
update employees set MobileNumber=8019249449	where empid=933	;
update employees set MobileNumber=8143655453	where empid=930	;
update employees set MobileNumber=8096366512	where empid=932	;
update employees set MobileNumber=7702536933	where empid=945	;
update employees set MobileNumber=9705581099	where empid=943	;

update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=555;
update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=565;
update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=708;
update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=777;
update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=785;
update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=563;
update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=822;
update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=574;
update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=744;
update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=564;
update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=800;
update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=560;
update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=554;
update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=580;
update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=557;
update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=575;
update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=788;
update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=566;
update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=817;
update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=547;
update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=548;
update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=721;
update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=789;
update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=779;
update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=562;
update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=586;
update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=590;
update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=782;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=827;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=790;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=749;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=723;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=714;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=793;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=731;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=775;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=733;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=801;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=549;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=804;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=730;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=581;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=559;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=570;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=702;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=783;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=599;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=725;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=830;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=786;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=796;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=550;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=572;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=760;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=709;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=556;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=805;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=814;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=598;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=763;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=815;
update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=835;
update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=840;
update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=845;
update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=876;
update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=863;
update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=864;
update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=838;
update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=841;
update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=836;
update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=846;
update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=837;
update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=847;
update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=877;
update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=931;
update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=935;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=899;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=848;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=865;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=842;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=878;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=911;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=866;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=849;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=901;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=889;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=902;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=867;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=903;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=887;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=910;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=868;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=896;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=884;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=893;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=862;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=871;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=872;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=860;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=886;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=881;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=909;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=853;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=912;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=885;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=891;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=854;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=905;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=892;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=890;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=855;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=861;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=856;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=857;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=858;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=895;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=859;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=913;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=906;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=898;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=844;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=874;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=914;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=920;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=915;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=917;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=916;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=918;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=921;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=922;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=924;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=925;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=926;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=928;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=929;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=941;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=942;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=944;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=946;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=948;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=949;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=938;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=939;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=937;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=936;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=934;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=933;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=930;
update employees set JoinedDesignation=(select id from designations where name='Staff Assistant') where empid=932;
update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=945;
update employees set JoinedDesignation=(select id from designations where name='Manager Scale-1') where empid=943;

update employees set currentDesignation=(select id from designations where name='Senior Manager') where empid=555	;
update employees set currentDesignation=(select id from designations where name='Senior Manager') where empid=565	;
update employees set currentDesignation=(select id from designations where name='Senior Manager') where empid=708	;
update employees set currentDesignation=(select id from designations where name='Senior Manager') where empid=777	;
update employees set currentDesignation=(select id from designations where name='Senior Manager') where empid=785	;
update employees set currentDesignation=(select id from designations where name='Senior Manager') where empid=563	;
update employees set currentDesignation=(select id from designations where name='Senior Manager') where empid=822	;
update employees set currentDesignation=(select id from designations where name='Senior Manager') where empid=574	;
update employees set currentDesignation=(select id from designations where name='Senior Manager') where empid=744	;
update employees set currentDesignation=(select id from designations where name='Senior Manager') where empid=564	;
update employees set currentDesignation=(select id from designations where name='Senior Manager') where empid=800	;
update employees set currentDesignation=(select id from designations where name='Senior Manager') where empid=560	;
update employees set currentDesignation=(select id from designations where name='Senior Manager') where empid=554	;
update employees set currentDesignation=(select id from designations where name='Senior Manager') where empid=580	;
update employees set currentDesignation=(select id from designations where name='Senior Manager') where empid=557	;
update employees set currentDesignation=(select id from designations where name='Senior Manager') where empid=575	;
update employees set currentDesignation=(select id from designations where name='Senior Manager') where empid=788	;
update employees set currentDesignation=(select id from designations where name='Senior Manager') where empid=566	;
update employees set currentDesignation=(select id from designations where name='Senior Manager') where empid=817	;
update employees set currentDesignation=(select id from designations where name='Senior Manager') where empid=547	;
update employees set currentDesignation=(select id from designations where name='Senior Manager') where empid=548	;
update employees set currentDesignation=(select id from designations where name='Senior Manager') where empid=721	;
update employees set currentDesignation=(select id from designations where name='Senior Manager') where empid=789	;
update employees set currentDesignation=(select id from designations where name='Senior Manager') where empid=779	;
update employees set currentDesignation=(select id from designations where name='Senior Manager') where empid=562	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=586	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=590	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=782	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=827	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=790	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=749	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=723	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=714	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=793	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=731	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=775	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=733	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=801	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=549	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=804	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=730	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=581	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=559	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=570	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=702	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=783	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=599	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=725	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=830	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=786	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=796	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=550	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=572	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=760	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=709	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=556	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=805	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=814	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=598	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=763	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=815	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=835	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=840	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=845	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=876	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=863	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=864	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=838	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=841	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=836	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=846	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=837	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=847	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=877	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=931	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=935	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=899	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=848	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=865	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=842	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=878	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=911	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=866	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=849	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=901	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=889	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=902	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=867	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=903	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=887	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=910	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=868	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=896	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=884	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=893	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=862	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=871	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=872	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=860	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=886	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=881	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=909	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=853	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=912	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=885	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=891	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=854	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=905	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=892	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=890	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=855	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=861	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=856	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=857	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=858	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=895	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=859	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=913	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=906	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=898	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=844	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=874	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=914	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=920	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=915	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=917	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=916	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=918	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=921	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=922	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=924	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=925	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=926	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=928	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=929	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=941	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=942	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=944	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=946	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=948	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=949	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=938	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=939	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=937	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=936	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=934	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=933	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=930	;
update employees set currentDesignation=(select id from designations where name='Staff Assistant') where empid=932	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=945	;
update employees set currentDesignation=(select id from designations where name='Manager Scale-1') where empid=943	;

