drop INDEX PoldLoanDet.idx_LoanId_PoldLoanDet
drop INDEX PoldLoanDet.idx_priority_PoldLoanDet
drop INDEX PoldLoanDet.idx_pmonth_PoldLoanDet
drop INDEX PoldLoan.idx_LoanId_PoldLoan 
drop INDEX PoldLoan.idx_pmonth_PoldLoan 
drop INDEX PoldLoan.idx_eid_PoldLoan 
drop INDEX plenc2018.idx_eid_plenc2018
drop INDEX codint2015.idx_eid_codint2015
drop INDEX PLicMast.idx_eid_PLicMast
drop INDEX QrepLoan.idx_eid_QrepLoan
drop INDEX pemptrainbak.idx_eid_pemptrainbak
drop INDEX HBLHOUS1.idx_eid_HBLHOUS1
drop INDEX QrLoanrep.idx_eid_QrLoanrep
drop INDEX sampir$.idx_eid_sampir$
drop INDEX ALL_LOAN_INTNO.idx_eid_ALL_LOAN_INTNO
drop INDEX FGPRM.idx_eid_FGPRM
drop INDEX med2020$.idx_eid_med2020$
drop INDEX Qrepadj.idx_eid_Qrepadj
drop INDEX pempfamilybak.idx_eid_pempfamilybak
drop INDEX BANKACNO.idx_eid_BANKACNO
drop INDEX med20201$.idx_eid_med20201$
drop INDEX Finperiod.idx_eid_Finperiod
drop INDEX pempprom.idx_eid_pempprom
drop INDEX pep010216.idx_eid_pep010216
drop INDEX PLeaveprm.idx_eid_PLeaveprm
drop INDEX hlins2014.idx_eid_hlins2014
drop INDEX EXT$.idx_eid_EXT$
drop INDEX hlins2014.idx_eid_hlins2014

drop INDEX PLEAVE.idx_eid_PLeave
drop INDEX Sheet1.idx_eid_Sheet1
drop INDEX PHistprm.idx_eid_PHistprm
drop INDEX stpf_10_20.idx_eid_stpf_10_20
drop INDEX Pempincr.idx_eid_Pempincr
drop INDEX PEMPMAST12.idx_eid_PEMPMAST12
drop INDEX pep0316.idx_eid_pep0316
drop INDEX TBL_FESTLOAN.idx_eid_TBL_FESTLOAN
drop INDEX PEmpHist.idx_eid_PEmpHist
drop INDEX PfOpBal.idx_eid_PfOpBal
drop INDEX PEmpTrans.idx_eid_PEmpTrans
drop INDEX PLoan_20110527.idx_eid_PLoan_20110527
drop INDEX pbasicstruc.idx_eid_pbasicstruc
drop INDEX POldEmpMast.idx_eid_POldEmpMast
drop INDEX PEmpprm.idx_eid_PEmpprm
drop INDEX enc0112.idx_eid_enc0112
drop INDEX Netarr.idx_eid_Netarr
drop INDEX POldAdjust_20110527.idx_eid_POldAdjust_20110527
drop INDEX PEmpPF.idx_eid_PEmpPF
drop INDEX PFopenold.idx_eid_PFopenold
drop INDEX PRevsal.idx_eid_PRevsal
drop INDEX PHoliDayList.idx_eid_PHoliDayList
drop INDEX taxrefund.idx_eid_taxrefund
drop INDEX PPayLICDet.idx_eid_PPayLICDet
drop INDEX pep0416.idx_eid_pep0416
drop INDEX PEP_MISC.idx_eid_PEP_MISC
drop INDEX PREPCOL.idx_eid_PREPCOL
drop INDEX PAllowanceprm.idx_eid_PAllowanceprm
drop INDEX codins17.idx_eid_codins17
drop INDEX PREPCOND.idx_eid_PREPCOND
drop INDEX XXXX.idx_eid_XXXX
drop INDEX pep0118.idx_eid_pep0118
drop INDEX PLoanAdj_20110527.idx_eid_PLoanAdj_20110527
drop INDEX pep0103.idx_eid_pep0103
drop INDEX pep0715.idx_eid_pep0715
drop INDEX pep0405.idx_eid_pep0405
drop INDEX Sheet1$.idx_eid_Sheet1$
drop INDEX PREPMAST.idx_eid_PREPMAST
drop INDEX TBL_ITJAN11.idx_eid_TBL_ITJAN11
drop INDEX vehins18.idx_eid_vehins18
drop INDEX encash_april.idx_eid_encash_april
drop INDEX PEncash_1st_batch.idx_eid_PEncash_1st_batch
drop INDEX pep_0815.idx_eid_pep_0815
drop INDEX pep052016.idx_eid_pep052016
drop INDEX tblempmast.idx_eid_tblempmast
drop INDEX PIMPFRMT.idx_eid_PIMPFRMT
drop INDEX pemptrain.idx_eid_pemptrain
drop INDEX codint.idx_eid_codint
drop INDEX PSUBLOAN.idx_eid_PSUBLOAN
drop INDEX MA0616.idx_eid_MA0616
drop INDEX PROIChange.idx_eid_PROIChange
drop INDEX PIMPDET.idx_eid_PIMPDET
drop INDEX dumpf2018.idx_eid_dumpf2018
drop INDEX ex2019$.idx_eid_ex2019$
drop INDEX pep0616.idx_eid_pep0616
drop INDEX exg2018$.idx_eid_exg2018$
drop INDEX PCCTrans.idx_eid_PCCTrans
drop INDEX club.idx_eid_club
drop INDEX medical_arr.idx_eid_medical_arr
drop INDEX cea_1.idx_eid_cea_1
drop INDEX earnings.idx_eid_earnings
drop INDEX Reg111$.idx_eid_Reg111$
drop INDEX PItVal.idx_eid_PItVal
drop INDEX exgratia2018.idx_eid_exgratia2018
drop INDEX PCCVal.idx_eid_PCCVal
drop INDEX med$.idx_eid_med$
drop INDEX TBL_PFLoans.idx_eid_TBL_PFLoans
drop INDEX FA912.idx_eid_FA912
drop INDEX exgt$.idx_eid_exgt$
drop INDEX pep062016.idx_eid_pep062016
drop INDEX fest0912.idx_eid_fest0912
drop INDEX POLDLEAVE.idx_eid_POLDLEAVE
drop INDEX PCCId.idx_eid_PCCId
drop INDEX PSet.idx_eid_PSet
drop INDEX TBL_OTHERLOANS_201005.idx_eid_TBL_OTHERLOANS_201005
drop INDEX TblAllowprmChangelog.idx_eid_TblAllowprmChangelog
drop INDEX pep0108.idx_eid_pep0108
drop INDEX FA030915.idx_eid_FA030915
drop INDEX TBL_FA910.idx_eid_TBL_FA910
drop INDEX FA0915_2.idx_eid_FA0915_2
drop INDEX PREPFLD.idx_eid_PREPFLD
drop INDEX fest0914.idx_eid_fest0914
drop INDEX pep1008.idx_eid_pep1008
drop INDEX PAllowancemast.idx_eid_PAllowancemast
drop INDEX PItPrm.idx_eid_PItPrm
drop INDEX TBL_codins0111.idx_eid_TBL_codins0111
drop INDEX PIt12B.idx_eid_PIt12B
drop INDEX PEmpmastMAYDATA.idx_eid_PEmpmastMAYDATA
drop INDEX TBL_HLPRM.idx_eid_TBL_HLPRM
drop INDEX pepda.idx_eid_pepda
drop INDEX PLoan.idx_eid_PLoan
drop INDEX PLoan.idx_LoanId_PLoan
drop INDEX pep0815.idx_eid_pep0815
drop INDEX tbl_fgprm0111.idx_eid_tbl_fgprm0111
drop INDEX tbl_HLPRM1.idx_eid_tbl_HLPRM1
drop INDEX pepw0716.idx_eid_pepw0716
drop INDEX exgratia2015.idx_eid_exgratia2015
drop INDEX TBL_CUSTID.idx_eid_TBL_CUSTID
drop INDEX exgratia_ts_2015.idx_eid_exgratia_ts_2015
drop INDEX PLeavereg.idx_eid_PLeavereg
drop INDEX houins15.idx_eid_houins15
drop INDEX PGlHeads.idx_eid_PGlHeads
drop INDEX fest1014.idx_eid_fest1014

drop INDEX fest1014.idx_eid_fest1014
drop INDEX PAdhslip.idx_eid_PAdhslip
drop INDEX loanperks.idx_eid_loanperks
drop INDEX houins.idx_eid_houins
drop INDEX codperks20$.idx_eid_codperks20$                                 
drop INDEX pep1016.idx_eid_pep1016                                     
drop INDEX PLoanAdj.idx_eid_PLoanAdj                                    
drop INDEX LEAVES0911.idx_eid_LEAVES0911                                  
drop INDEX wa1016.idx_eid_wa1016                                      
drop INDEX PLoanDet.idx_eid_PLoanDet                                    
drop INDEX leaves0811.idx_eid_leaves0811                                  
drop INDEX POldAdjust.idx_eid_POldAdjust                                  
drop INDEX PoldLoan.idx_eid_PoldLoan                                    
drop INDEX POldLoan.idx_eid_POldLoan                                    
drop INDEX PoldLoanDet.idx_eid_PoldLoanDet                                 
drop INDEX ppayEnter.idx_eid_ppayEnter                                   
drop INDEX med0117.idx_eid_med0117                                     
drop INDEX POldLoanDet.idx_eid_POldLoanDet                                 
drop INDEX PoldLoan.idx_eid_PoldLoan                                    
drop INDEX TBL_LOANSNOVDED.idx_eid_TBL_LOANSNOVDED                             
drop INDEX PoldLoanDet.idx_eid_PoldLoanDet                                 
drop INDEX pleavebcup.idx_eid_pleavebcup                                  
			
drop INDEX PLoanDet_20110527.idx_eid_PLoanDet_20110527                           
drop INDEX PLeaveregBackUp.idx_eid_PLeaveregBackUp                             
drop INDEX PFopen.idx_eid_PFopen                                      
drop INDEX PItOther.idx_eid_PItOther                                    
drop INDEX TBL_PFNR.idx_eid_TBL_PFNR                                    
drop INDEX POldLoanDet.idx_eid_POldLoanDet                                 
drop INDEX CODINS2014.idx_eid_CODINS2014                                  
drop INDEX PItDet.idx_eid_PItDet                                      
drop INDEX tblPEmpMastDOJNull.idx_eid_tblPEmpMastDOJNull                          
drop INDEX TBL_LTMONTHLYUSEDLEAVEDETAILS.idx_eid_TBL_LTMONTHLYUSEDLEAVEDETAILS               
drop INDEX PEMPMAST.idx_eid_PEMPMAST                                    
drop INDEX TBL_STMONTHLYUSEDLEAVES.idx_eid_TBL_STMONTHLYUSEDLEAVES                     
drop INDEX PEmpLICDet.idx_eid_PEmpLICDet                                  
drop INDEX one.idx_eid_one                                         
drop INDEX PempFamily.idx_eid_PempFamily                                  
drop INDEX TBL_PFNO.idx_eid_TBL_PFNO                                    
drop INDEX POldslip.idx_eid_POldslip                                    
			
drop INDEX tblEmpMastChangeLog.idx_eid_tblEmpMastChangeLog                         
drop INDEX PIncDtChg.idx_eid_PIncDtChg                                   
drop INDEX CODPremium.idx_eid_CODPremium                                  
drop INDEX CODPremium17.idx_eid_CODPremium17                                
drop INDEX PItCal.idx_eid_PItCal                                      
drop INDEX vehins2014.idx_eid_vehins2014                                  
drop INDEX PFwithdraw.idx_eid_PFwithdraw                                  
drop INDEX fgprm2014.idx_eid_fgprm2014                                   
drop INDEX incent_13_14.idx_eid_incent_13_14                                
drop INDEX vehins2017.idx_eid_vehins2017                                  
drop INDEX PEncashment.idx_eid_PEncashment                                 
drop INDEX PEncash.idx_eid_PEncash                                     
drop INDEX PPFApprisal.idx_eid_PPFApprisal                                 
drop INDEX PLeave.idx_eid_PLeave                                      
drop INDEX CODINS_2015.idx_eid_CODINS_2015                                 
drop INDEX FGPRM2015.idx_eid_FGPRM2015                                   
drop INDEX sal1617.idx_eid_sal1617                                     
drop INDEX PAdjust.idx_eid_PAdjust                                     
drop INDEX enc1617.idx_eid_enc1617                                     
drop INDEX adh1617.idx_eid_adh1617                                     
drop INDEX codint2017.idx_eid_codint2017                                  
drop INDEX hlins.idx_eid_hlins                                       
drop INDEX EXGRATIA.idx_eid_EXGRATIA                                    
drop INDEX pfts2016.idx_eid_pfts2016                                    
drop INDEX PLeave.idx_eid_PLeave                                      
drop INDEX HOUPROPINS.idx_eid_HOUPROPINS                                  
drop INDEX non_refAdvances.idx_eid_non_refAdvances                             
drop INDEX STAFF_AR.idx_eid_STAFF_AR                                    
drop INDEX PIT12BA.idx_eid_PIT12BA                                     
drop INDEX PEmpOthDet.idx_eid_PEmpOthDet                                  
drop INDEX ptdsslip.idx_eid_ptdsslip                                    
drop INDEX PEmpmastOLD.idx_eid_PEmpmastOLD                                 
drop INDEX ltassnlevy.idx_eid_ltassnlevy                                  
drop INDEX STAFF_TR.idx_eid_STAFF_TR                                    
drop INDEX PPayOthDet.idx_eid_PPayOthDet                                  
drop INDEX unionlevy.idx_eid_unionlevy                                   
drop INDEX CODPERKS14.idx_eid_CODPERKS14                                  
drop INDEX VEH_INS_2015.idx_eid_VEH_INS_2015                                
drop INDEX PLEAVE.idx_eid_PLEAVE                                      
drop INDEX JULY.idx_eid_JULY                                        
drop INDEX PPayslip.idx_eid_PPayslip                                    
drop INDEX Reppayslip.idx_eid_Reppayslip                                  
drop INDEX LOANPERKS_0315.idx_eid_LOANPERKS_0315                              
drop INDEX houins17.idx_eid_houins17                                    
drop INDEX ret_emp_pfint.idx_eid_ret_emp_pfint                               
drop INDEX codins.idx_eid_codins                                      
drop INDEX PItCal1920.idx_eid_PItCal1920                                  
drop INDEX INCENTIVE2013.idx_eid_INCENTIVE2013                               
drop INDEX PItOther1920.idx_eid_PItOther1920                                
drop INDEX ret_lt_emp_pfint.idx_eid_ret_lt_emp_pfint                            
drop INDEX fgprm2013.idx_eid_fgprm2013                                   
drop INDEX pgrautity.idx_eid_pgrautity                                   
drop INDEX PItVal1920.idx_eid_PItVal1920                                  
drop INDEX PLeave20110917.idx_eid_PLeave20110917                              
drop INDEX vehins.idx_eid_vehins                                      
drop INDEX PEmpmastindexproblem.idx_eid_PEmpmastindexproblem                        
drop INDEX codperks19$.idx_eid_codperks19$                                 
drop INDEX PArrears.idx_eid_PArrears                                    
drop INDEX codperks.idx_eid_codperks                                    
drop INDEX CODINS2016.idx_eid_CODINS2016                                  
drop INDEX adhocrgv$.idx_eid_adhocrgv$                                   
drop INDEX vehins2016.idx_eid_vehins2016                                  
drop INDEX onedaysal911.idx_eid_onedaysal911                                
drop INDEX ppp.idx_eid_ppp                                         
drop INDEX rrr.idx_eid_rrr                                         
			
drop INDEX PGPFDet.idx_eid_PGPFDet                                     
drop INDEX CODINSPRM.idx_eid_CODINSPRM                                   
drop INDEX PEmpmastSECONDTIMEINDEXPROBLEM.idx_eid_PEmpmastSECONDTIMEINDEXPROBLEM              
drop INDEX PEmpmast1.idx_eid_PEmpmast1                                   
drop INDEX Pempqual.idx_eid_Pempqual                                    
drop INDEX pempqualbak.idx_eid_pempqualbak                                 
drop INDEX tbl_VEH.idx_eid_tbl_VEH                                 
