CREATE TABLE [dbo].[dm_emp_mn_task](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[emp_code] [int] NOT NULL,
	[mn] [int] NOT NULL,
	[task] [nvarchar](500) NOT NULL,
 CONSTRAINT [PK_dm_emp_mn_task] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
