insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 121),183);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 147),94);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 176),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 204),331);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 240),101);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 254),321);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 265),60);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 266),145);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 279),322);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 286),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 292),150);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 293),274);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 301),6);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 302),112);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 308),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 319),97);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 331),7);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 338),279);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 340),64);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 356),147);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 358),260);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 361),11);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 363),144);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 364),250);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 365),344);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 371),109);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 376),98);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 377),83);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 381),122);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 421),138);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 428),96);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 429),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 438),311);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 440),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 445),35);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 452),93);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 457),258);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 460),104);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 468),58);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 474),250);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 476),106);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 478),89);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 480),58);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 484),185);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 491),19);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 492),150);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 499),140);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 507),95);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 510),32);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 511),93);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 513),102);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 514),73);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 518),89);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 519),102);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 521),94);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 523),28);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 526),77);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 527),113);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 528),116);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 530),118);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 532),60);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 534),109);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 538),71);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 545),51);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 547),32);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 548),52);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 5802),317);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 373),161);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 556),42);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 539),109);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 337),199);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 304),219);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 5741),159);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 5781),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 5909),98);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 940),20);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 509),47);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 6190),192);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 1998),176);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 5148),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 6195),122);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 6193),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 5809),192);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 5750),214);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 5882),274);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 5888),19);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 5751),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 5660),59);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 6198),25);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 5757),353);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 6182),29);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 5161),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 6180),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 5770),1);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 5150),291);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 6194),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 5884),129);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 5768),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 5866),126);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 5794),287);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 1862),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 6196),27);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 5908),168);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 1930),30);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 5796),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 6177),235);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 6209),223);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 444),46);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 520),73);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 486),49);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 485),88);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 427),57);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 5889),37);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 6199),172);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 6191),219);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 5738),159);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 543),70);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 832),60);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 536),74);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 834),40);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 434),102);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 517),105);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 508),79);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 5782),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 5785),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 175),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 6173),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 493),225);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 374),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 383),301);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 686),215);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 462),182);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 368),133);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 354),334);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 405),251);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 271),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 463),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 359),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 320),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 287),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 357),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 5780),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 322),105);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 6184),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 262),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 5920),322);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 318),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 516),114);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 6192),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 5910),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 299),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 233),119);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 184),346);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 420),238);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 433),139);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 505),18);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 177),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 5746),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 6132),64);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 425),132);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 5824),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 178),28);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 422),189);

insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 239),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 250),70);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 288),299);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 303),237);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 490),15);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 5740),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 435),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 535),116);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 544),11);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 831),60);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 525),119);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 5743),253);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 249),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 512),51);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 5862),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 443),188);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 5869),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 5890),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 436),93);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 439),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 950),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 833),40);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 555),42);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 565),51);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 708),31);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 777),41);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 785),37);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 563),37);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 822),52);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 574),60);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 744),25);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 564),44);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 800),46);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 560),55);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 554),63);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 580),19);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 557),54);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 575),51);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 788),42);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 566),54);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 817),65);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 721),48);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 779),25);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 562),39);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 586),42);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 590),46);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 782),20);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 789),25);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 827),29);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 790),41);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 749),60);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 723),60);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 714),48);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 793),50);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 731),59);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 775),47);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 733),49);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 801),44);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 549),60);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 804),46);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 730),34);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 581),49);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 559),57);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 570),54);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 702),56);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 783),36);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 599),28);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 725),44);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 830),53);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 786),57);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 796),30);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 550),60);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 572),48);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 760),37);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 709),45);

insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 805),52);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 814),56);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 598),55);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 763),54);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 815),48);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 835),20);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 840),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 845),40);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 876),40);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 863),40);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 864),38);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 838),37);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 841),20);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 836),40);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 846),40);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 837),40);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 847),40);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 877),40);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 931),20);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 935),20);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 899),36);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 848),40);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 865),34);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 842),40);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 878),40);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 911),24);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 866),40);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 849),40);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 901),31);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 889),40);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 902),32);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 867),40);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 903),18);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 887),40);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 910),40);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 868),30);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 896),30);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 884),40);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 893),38);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 862),37);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 871),26);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 872),38);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 860),40);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 886),40);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 881),40);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 909),40);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 853),40);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 912),40);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 885),40);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 891),22);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 854),40);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 905),40);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 892),37);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 890),23);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 855),40);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 861),40);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 856),27);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 857),40);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 858),40);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 895),40);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 859),40);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 913),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 906),40);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 898),40);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 844),40);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 874),25);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 914),40);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 920),32);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 915),40);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 917),40);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 916),40);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 918),40);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 921),20);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 922),20);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 924),20);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 925),20);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 926),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 928),20);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 929),15);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 941),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 942),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 944),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 946),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 948),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 949),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 938),20);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 939),20);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 937),16);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 936),20);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 934),20);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 933),12);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 930),20);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 932),20);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 945),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 432),214);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 495),30);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 2005),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 943),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 6342),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 952),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 954),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 955),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 956),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 957),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 960),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 963),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 959),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 965),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 966),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 971),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 974),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 983),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 982),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 981),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 989),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 990),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 986),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 985),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 987),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 988),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 6303),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 6304),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 999),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 6300),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 6301),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 984),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 991),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 6302),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 6305),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 6317),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 6318),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 6319),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 6325),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 6332),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 6333),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 6334),0);

insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid= 947),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=951),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=953),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=958),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=962),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=961),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=967),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=968),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=970),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=969),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=972),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=973),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=976),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=975),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=977),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=979),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=980),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=978),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=995),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=997),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=992),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=996),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=993),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=998),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=994),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6309),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=964),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6306),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6308),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6315),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6316),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6307),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6311),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6313),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6310),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6312),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6314),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6320),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6321),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6323),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6322),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6324),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6326),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6327),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6329),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6328),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6330),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6331),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6335),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6336),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6337),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6338),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6339),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6340),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6341),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6343),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6344),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6345),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6354),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6351),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6352),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6353),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6346),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6350),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6347),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6348),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6349),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6357),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6355),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6356),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6358),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6359),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6360),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6361),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6366),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6362),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6367),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6368),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6369),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6363),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6364),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6365),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6370),0);
insert into empleavebalance values((select id from leavetypes where code='ML'),(select id from employees where empid=6372),0);

