insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 121),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 147),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 176),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 204),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 240),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 254),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 265),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 266),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 279),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 286),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 292),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 293),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 301),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 302),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 308),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 319),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 331),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 338),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 340),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 356),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 358),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 361),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 363),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 364),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 365),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 371),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 376),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 377),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 381),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 421),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 428),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 429),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 438),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 440),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 445),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 452),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 457),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 460),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 468),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 474),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 476),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 478),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 480),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 484),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 491),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 492),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 499),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 507),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 510),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 511),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 513),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 514),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 518),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 519),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 521),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 523),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 526),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 527),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 528),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 530),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 532),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 534),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 538),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 545),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 547),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 548),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 5802),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 373),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 556),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 539),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 337),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 304),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 5741),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 5781),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 5909),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 940),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 509),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 6190),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 1998),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 5148),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 6195),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 6193),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 5809),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 5750),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 5882),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 5888),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 5751),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 5660),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 6198),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 5757),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 6182),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 5161),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 6180),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 5770),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 5150),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 6194),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 5884),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 5768),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 5866),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 5794),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 1862),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 6196),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 5908),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 1930),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 5796),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 6177),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 6209),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 444),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 520),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 486),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 485),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 427),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 5889),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 6199),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 6191),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 5738),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 543),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 832),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 536),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 834),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 434),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 517),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 508),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 5782),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 5785),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 175),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 6173),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 493),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 374),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 383),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 686),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 462),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 368),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 354),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 405),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 271),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 463),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 359),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 320),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 287),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 357),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 5780),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 322),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 6184),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 262),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 5920),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 318),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 516),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 6192),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 5910),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 299),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 233),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 184),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 420),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 433),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 505),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 177),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 5746),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 6132),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 425),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 5824),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 178),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 422),0);

insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 239),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 250),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 288),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 303),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 490),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 5740),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 435),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 535),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 544),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 831),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 525),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 5743),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 249),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 512),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 5862),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 443),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 5869),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 5890),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 436),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 439),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 950),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 833),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 555),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 565),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 708),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 777),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 785),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 563),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 822),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 574),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 744),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 564),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 800),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 560),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 554),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 580),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 557),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 575),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 788),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 566),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 817),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 721),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 779),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 562),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 586),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 590),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 782),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 789),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 827),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 790),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 749),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 723),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 714),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 793),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 731),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 775),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 733),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 801),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 549),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 804),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 730),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 581),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 559),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 570),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 702),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 783),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 599),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 725),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 830),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 786),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 796),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 550),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 572),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 760),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 709),0);

insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 805),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 814),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 598),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 763),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 815),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 835),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 840),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 845),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 876),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 863),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 864),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 838),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 841),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 836),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 846),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 837),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 847),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 877),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 931),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 935),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 899),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 848),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 865),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 842),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 878),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 911),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 866),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 849),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 901),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 889),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 902),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 867),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 903),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 887),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 910),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 868),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 896),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 884),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 893),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 862),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 871),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 872),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 860),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 886),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 881),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 909),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 853),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 912),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 885),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 891),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 854),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 905),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 892),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 890),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 855),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 861),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 856),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 857),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 858),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 895),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 859),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 913),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 906),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 898),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 844),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 874),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 914),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 920),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 915),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 917),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 916),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 918),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 921),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 922),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 924),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 925),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 926),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 928),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 929),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 941),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 942),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 944),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 946),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 948),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 949),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 938),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 939),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 937),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 936),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 934),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 933),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 930),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 932),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 945),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 432),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 495),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 2005),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 943),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 6342),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 952),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 954),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 955),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 956),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 957),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 960),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 963),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 959),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 965),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 966),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 971),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 974),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 983),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 982),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 981),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 989),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 990),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 986),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 985),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 987),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 988),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 6303),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 6304),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 999),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 6300),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 6301),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 984),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 991),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 6302),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 6305),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 6317),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 6318),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 6319),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 6325),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 6332),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 6333),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 6334),0);

insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid= 947),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=951),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=953),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=958),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=962),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=961),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=967),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=968),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=970),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=969),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=972),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=973),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=976),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=975),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=977),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=979),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=980),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=978),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=995),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=997),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=992),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=996),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=993),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=998),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=994),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6309),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=964),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6306),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6308),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6315),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6316),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6307),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6311),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6313),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6310),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6312),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6314),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6320),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6321),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6323),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6322),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6324),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6326),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6327),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6329),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6328),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6330),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6331),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6335),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6336),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6337),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6338),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6339),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6340),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6341),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6343),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6344),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6345),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6354),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6351),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6352),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6353),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6346),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6350),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6347),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6348),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6349),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6357),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6355),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6356),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6358),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6359),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6360),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6361),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6366),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6362),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6367),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6368),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6369),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6363),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6364),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6365),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6370),0);
insert into empleavebalance values((select id from leavetypes where code='MTL'),(select id from employees where empid=6372),0);
