
select 1 , (select count(1) from pr_allowance_field_master ), (select count(distinct id)  from pr_allowance_field_master) union all 
select 2 , (select count(1) from pr_basic_anual_incr_master ), (select count(distinct id)  from pr_basic_anual_incr_master) union all
select 3 , (select count(1) from pr_basic_stag_incr_master ), (select count(distinct id)  from pr_basic_stag_incr_master) union all 
select 4 , (select count(1) from pr_branch_allowance_master ), (select count(distinct id)  from pr_branch_allowance_master) union all 
select 5 , (select count(1) from pr_contribution_field_master ), (select count(distinct id)  from pr_contribution_field_master) union all
select 6 , (select count(1) from pr_deduction_field_master ), (select count(distinct id)  from pr_deduction_field_master) union all
select 7 , (select count(1) from pr_earn_field_master ), (select count(distinct id)  from pr_earn_field_master) union all 
select 8 , (select count(1) from pr_emp_adhoc_contribution_field ), (select count(distinct id)  from pr_emp_adhoc_contribution_field) union all
select 9 , (select count(1) from pr_emp_adhoc_deduction_field ), (select count(distinct id)  from pr_emp_adhoc_deduction_field) union all
select 10 , (select count(1) from pr_emp_adhoc_det_field ), (select count(distinct id)  from pr_emp_adhoc_det_field) union all 
select 11 , (select count(1) from pr_emp_adhoc_earn_field ), (select count(distinct id)  from pr_emp_adhoc_earn_field) union all 
select 12 , (select count(1) from pr_emp_adj_contribution_field ), (select count(distinct id)  from pr_emp_adj_contribution_field) union all
select 13 , (select count(1) from pr_emp_adj_deduction_field ), (select count(distinct id)  from pr_emp_adj_deduction_field) union all
select 14 , (select count(1) from pr_emp_adj_earn_field ), (select count(distinct id)  from pr_emp_adj_earn_field) union all
select 15 , (select count(1) from pr_emp_adv_loan_type ), (select count(distinct id)  from pr_emp_adv_loan_type) union all
select 16 , (select count(1) from pr_emp_adv_loans ), (select count(distinct id)  from pr_emp_adv_loans) union all 
select 17 , (select count(1) from pr_emp_adv_loans_adjustments ), (select count(distinct id)  from pr_emp_adv_loans_adjustments) union all 
select 18 , (select count(1) from pr_emp_adv_loans_adjustments_bef_monthend ), (select count(distinct id)  from pr_emp_adv_loans_adjustments_bef_monthend) union all 
select 19 , (select count(1) from pr_emp_adv_loans_bef_monthend ), (select count(distinct id)  from pr_emp_adv_loans_bef_monthend) union all 
select 20 , (select count(1) from pr_emp_adv_loans_child ), (select count(distinct id)  from pr_emp_adv_loans_child) union all 
select 21 , (select count(1) from pr_emp_adv_loans_child_bef_monthend ), (select count(distinct id)  from pr_emp_adv_loans_child_bef_monthend) union all
select 22 , (select count(1) from pr_emp_allowance_process ), (select count(distinct id)  from pr_emp_allowance_process) union all
select 23 , (select count(1) from pr_emp_allowances ), (select count(distinct id)  from pr_emp_allowances) union all
select 24 , (select count(1) from pr_emp_allowances_gen ), (select count(distinct id)  from pr_emp_allowances_gen) union all 
select 25 , (select count(1) from pr_emp_allowances_spl ), (select count(distinct id)  from pr_emp_allowances_spl) union all 
select 26 , (select count(1) from pr_emp_branch_allowances ), (select count(distinct id)  from pr_emp_branch_allowances) union all
select 27 , (select count(1) from pr_emp_categories ), (select count(distinct id)  from pr_emp_categories) union all
select 28 , (select count(1) from pr_emp_deductions ), (select count(distinct id)  from pr_emp_deductions) union all
select 29 , (select count(1) from pr_emp_deput_contribution_field ), (select count(distinct id)  from pr_emp_deput_contribution_field) union all 
select 30 , (select count(1) from pr_emp_deput_deduction_field ), (select count(distinct id)  from pr_emp_deput_deduction_field) union all
select 31 , (select count(1) from pr_emp_deput_det_field ), (select count(distinct id)  from pr_emp_deput_det_field) union all 
select 32 , (select count(1) from pr_emp_designation ), (select count(distinct id)  from pr_emp_designation) union all 
select 33 , (select count(1) from pr_emp_epf_deduction_field ), (select count(distinct id)  from pr_emp_epf_deduction_field) union all 
select 34 , (select count(1) from pr_emp_epf_earn_field ), (select count(distinct id)  from pr_emp_epf_earn_field) union all 
select 35 , (select count(1) from pr_emp_hfc_details ), (select count(distinct id)  from pr_emp_hfc_details) union all 
select 36 , (select count(1) from pr_emp_inc_anual_stag ), (select count(distinct id)  from pr_emp_inc_anual_stag) union all 
select 37 , (select count(1) from pr_emp_inc_date_change ), (select count(distinct id)  from pr_emp_inc_date_change) union all 
select 38 , (select count(1) from pr_emp_incometax_12b ), (select count(distinct id)  from pr_emp_incometax_12b) union all 
select 39 , (select count(1) from pr_emp_incometax_12ba ), (select count(distinct id)  from pr_emp_incometax_12ba) union all 
select 40 , (select count(1) from pr_emp_incometax_12ba_master ), (select count(distinct id)  from pr_emp_incometax_12ba_master) union all
select 41 , (select count(1) from pr_emp_jaib_caib_general ), (select count(distinct id)  from pr_emp_jaib_caib_general) union all 
select 42 , (select count(1) from pr_emp_lic_details ), (select count(distinct id)  from pr_emp_lic_details) union all
select 43 , (select count(1) from pr_emp_loans_projection ), (select count(distinct id)  from pr_emp_loans_projection) union all
select 44 , (select count(1) from pr_emp_other_tds_deductions ), (select count(distinct id)  from pr_emp_other_tds_deductions) union all
select 45 , (select count(1) from pr_emp_pay_field ), (select count(distinct id)  from pr_emp_pay_field) union all
select 46 , (select count(1) from pr_emp_payslip ), (select count(distinct id)  from pr_emp_payslip) union all
select 47 , (select count(1) from pr_emp_payslip_allowance ), (select count(distinct id)  from pr_emp_payslip_allowance) union all 
select 48 , (select count(1) from pr_emp_payslip_deductions ), (select count(distinct id)  from pr_emp_payslip_deductions) union all
select 49 , (select count(1) from pr_emp_payslip_netSalary ), (select count(distinct id)  from pr_emp_payslip_netSalary) union all 
select 50 , (select count(1) from pr_emp_perdeductions ), (select count(distinct id)  from pr_emp_perdeductions) union all
select 51 , (select count(1) from pr_emp_perearning ), (select count(distinct id)  from pr_emp_perearning) union all 
select 52, (select count(1) from pr_emp_pf_non_cert_elg ), (select count(distinct id)  from pr_emp_pf_non_cert_elg) union all 
select 53 , (select count(1) from pr_emp_pf_nonrepayable_loan ), (select count(distinct id)  from pr_emp_pf_nonrepayable_loan) union all 
select 54 , (select count(1) from pr_emp_pf_repayable_loan ), (select count(distinct id)  from pr_emp_pf_repayable_loan) union all
select 55 , (select count(1) from pr_emp_promotion ), (select count(distinct id)  from pr_emp_promotion) union all 
select 56 , (select count(1) from pr_emp_rent_details ), (select count(distinct id)  from pr_emp_rent_details) union all 
select 57 , (select count(1) from pr_emp_tds_process ), (select count(distinct id)  from pr_emp_tds_process) union all 
select 58 , (select count(1) from pr_emp_tds_process_allowances ), (select count(distinct id)  from pr_emp_tds_process_allowances) union all 
select 59 , (select count(1) from pr_emp_tds_section_deductions ), (select count(distinct id)  from pr_emp_tds_section_deductions) union all 
select 60 , (select count(1) from pr_encashment_deductions_customization ), (select count(distinct id)  from pr_encashment_deductions_customization) union all 
select 61 , (select count(1) from pr_encashment_earnings_customization ), (select count(distinct id)  from pr_encashment_earnings_customization) union all 
select 62 , (select count(1) from pr_form16_codes ), (select count(distinct id)  from pr_form16_codes) union all 
select 63 , (select count(1) from pr_incometax_bank_payment ), (select count(distinct id)  from pr_incometax_bank_payment) union all 
select 64 , (select count(1) from pr_list_of_documents_master ), (select count(distinct id)  from pr_list_of_documents_master) union all 
select 65 , (select count(1) from pr_loan_master ), (select count(distinct id)  from pr_loan_master) union all 
select 66 , (select count(1) from pr_month_attendance ), (select count(distinct id)  from pr_month_attendance) union all 
select 67 , (select count(1) from pr_month_details ), (select count(distinct id)  from pr_month_details) union all 
select 68 , (select count(1) from pr_ob_share ), (select count(distinct id)  from pr_ob_share) union all 
select 69 , (select count(1) from pr_ob_share_adhoc ), (select count(distinct id)  from pr_ob_share_adhoc)  union all
select 70 , (select count(1) from pr_ob_share_encashment ), (select count(distinct id)  from pr_ob_share_encashment)  union all
select 71 , (select count(1) from pr_payroll_service_run ), (select count(distinct id)  from pr_payroll_service_run) union all
select 72 , (select count(1) from pr_payslip_customization ), (select count(distinct id)  from pr_payslip_customization) union all
select 73 , (select count(1) from pr_pf_nominee ), (select count(distinct id)  from pr_pf_nominee) union all 
select 74 , (select count(1) from pr_purpose_of_advance_master ), (select count(distinct id)  from pr_purpose_of_advance_master) union all 
select 75 , (select count(1) from pr_rentdetails_master ), (select count(distinct id)  from pr_rentdetails_master) 